### ISSUE TITLE
Provide Texture

### ISSUE THREAD

**Issue by Blank-1973** [Unity-Resource-Pack/Unity-Dark#9]
I intend to make it correctly, but please check and fix it
Provides [AE2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2),[WarpBook](https://www.curseforge.com/minecraft/mc-mods/warp-book),[WCT](https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal),[WFT](https://www.curseforge.com/minecraft/mc-mods/wireless-fluid-terminal),[WIT](https://www.curseforge.com/minecraft/mc-mods/wireless-interface-terminal),[WPT](https://www.curseforge.com/minecraft/mc-mods/wireless-pattern-terminal) texture

http://www.mediafire.com/file/329diokb5u40s0g/Unity-Dark-offer.zip/file

**Comment by CyanideX** [comment]
What versions of Minecraft do these support?

**Comment by TheSnowyChickens** [comment]
@CyanideX Looks like 1.12.2.

**Comment by CyanideX** [comment]
Unity Dark is currently targeting 1.16+ so we won't be pulling these in at the moment. I do appreciate the contribution and would be more than happy to accept these should they ever be updated to 1.16. 🙂

**Comment by TheSnowyChickens** [comment]
@CyanideX I installed the textures in 1.16.1 and they worked. (some textures are missing, compared with the list of GUIs from AE2 1.16.1 folder)
+ some text is slightly to dark in the GUIs, but I don't know how to fix that.

But all in all, you could use them to create a finished 1.16.1 AE2 dark mode design.

All the Wireless Terminals from p455w0rd are also in the provided folder of textures, that's why I said it is for 1.12.2.^^
